apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      #GrafanaPort #port: 3000
      #GrafanaPort #targetPort: 3000
      nodePort: 31000
      protocol: TCP
      name: http
  selector:
    run: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  replicas: 4
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web-app
        image: jenkins/jenkins:latest
        #image: grafana/grafana:latest
        ports:
        - containerPort: 80
