apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      #JenkinsPort #port: 8080
      #JenkinsPort #targetPort: 8080
      nodePort: 31000
      protocol: TCP
      name: http
  selector:
    run: web
