apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor
  namespace: harbor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
  template:
    metadata:
      labels:
        app: harbor
    spec:
      containers:
        - name: harbor
          image: goharbor/harbor-core:v2.11.0
          ports:
            - containerPort: 8080
          env:
            - name: CORE_SECRET
              value: "secret"
            - name: DATABASE_TYPE
              value: "postgresql"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
  namespace: harbor
spec:
  type: NodePort
  selector:
    app: harbor
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30002
